#!/usr/bin/env bash

# copy/link this file as "git-continue" to get analogous continue utility

opt="${0/*-/}"
gitdir="$(git rev-parse --git-dir)" || exit
opfound=
fcnt=
for i in cherry-pick merge rebase; do
  f=${i^^}
  f=${f/-/_}
  test -f "${gitdir}/${f}_HEAD" && fcnt=1$fcnt && opfound=$i
done

if [ "${fcnt}" != 1 ]; then
  echo "I don't know what to $opt" >&2
  exit 1
fi

git "${opfound}" --"$opt"
